name: Pre-commit

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  checks:
    uses: OxIonics/common-workflows/.github/workflows/common_pre_commit_checks.yml@master
    secrets:
      GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
