name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  checks:
    uses: OxIonics/common-workflows/.github/workflows/test_flake_black.yml@master
    secrets:
      GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
      PACKAGE_NAME: .
